import typescript from '@rollup/plugin-typescript';
import { nodeResolve } from '@rollup/plugin-node-resolve';
import commonjs from '@rollup/plugin-commonjs';
import copy from 'rollup-plugin-copy'; // <-- 1. IMPORT THE COPY PLUGIN

const isProd = (process.env.BUILD === 'production');

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ROLLUP
if you want to view the source visit the plugins github repository
*/
`;

export default {
  input: 'main.ts', // Your main.ts is in the root of CodeFolder
  output: {
    dir: '.',       // Output to the root of CodeFolder (main.js, styles.css, manifest.json)
    sourcemap: 'inline',
    sourcemapExcludeSources: isProd,
    format: 'cjs',
    exports: 'default',
    banner,
  },
  external: ['obsidian'],
  plugins: [
    typescript(),
    nodeResolve({ browser: true }),
    commonjs(),
    copy({ // <-- 2. ADD THE COPY PLUGIN CONFIGURATION
      targets: [
        // Copy bmc_qr.png from src/ to the output directory (which is '.')
        { src: 'src/bmc_qr.png', dest: '.' }

        // If you had an assets folder and wanted to copy everything from it:
        // { src: 'assets/*', dest: 'assets' }
        // Or if you wanted assets from src/assets/ to the root assets/ folder:
        // { src: 'src/assets/*', dest: 'assets' }
      ],
      // Optional: Set to true if you want to see output from the copy plugin
      // verbose: true, 
    })
  ]
};